<a href="https://colab.research.google.com/github/tselane2110/Computer-Vision/blob/main/lecture_1_8june2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# no dimension tensor
t0 = tf.constant(8)
print(t0)

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
# 1 dimensional tensor
t1 = tf.constant([1])
print(t1)

tf.Tensor([1], shape=(1,), dtype=int32)


In [ ]:
# 2 dimensional tensor
t2 = tf.constant([
                    [1, 5],
                    [25, 3],
                    [0, 0]
                ])
print(t2)

tf.Tensor(
[[ 1  5]
 [25  3]
 [ 0  0]], shape=(3, 2), dtype=int32)


In [ ]:
# 3 dimensional tensor
t3 = tf.constant(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ],
        [
            [25, 66],
            [38, 44],
            [29, 33]
        ],
        [
            [25, 66],
            [38, 44],
            [29, 33]
        ],
        [
            [25, 66],
            [38, 44],
            [29, 33]
        ]
    ]
)
print(t3)

# 4 - 2D tensors
# 3 - 1D tensors
# 2 - 0D tensors :)) as simple as that!

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[25 66]
  [38 44]
  [29 33]]

 [[25 66]
  [38 44]
  [29 33]]

 [[25 66]
  [38 44]
  [29 33]]], shape=(4, 3, 2), dtype=int32)


In [ ]:
# print "shapes" of tensors using the shape function!
print(t3.shape, t2.shape, t1.shape, t0.shape)

(4, 3, 2) (3, 2) (1,) ()
